apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-streams
  namespace: argocd
spec:
  destination:
    namespace: kafka-streams
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart
    repoURL: https://github.com/supersidor/kafka-stream.git
    targetRevision: HEAD
    helm:
      releaseName: kafka-streams
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: $ARGOCD_APP_REVISION_SHORT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
