apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-storage
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/supersidor/argocd
    path: manifests/rook-ceph-storage-config
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
