apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-main-1-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-rbd
  claimRef:
    name: pg-main-1-data
    namespace: cnpg-cluster-main
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      pool: k3s
      imageFeatures: layering
      csi.storage.k8s.io/pv/name: pg-main-1-data
      csi.storage.k8s.io/pvc/name: pg-main-1-data
      csi.storage.k8s.io/pvc/namespace: cnpg-cluster-main
    volumeHandle: 9dab7605-db09-435b-a10d-5e7b335addfd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-main-2-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-rbd
  claimRef:
    name: pg-main-2-data
    namespace: cnpg-cluster-main
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      pool: k3s
      imageFeatures: layering
      csi.storage.k8s.io/pv/name: pg-main-2-data
      csi.storage.k8s.io/pvc/name: pg-main-2-data
      csi.storage.k8s.io/pvc/namespace: cnpg-cluster-main
    volumeHandle: 7716b6b5-95ad-4ab6-a9c8-e8ccae3f08c4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-main-3-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-rbd
  claimRef:
    name: pg-main-3-data
    namespace: cnpg-cluster-main
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      pool: k3s
      imageFeatures: layering
      csi.storage.k8s.io/pv/name: pg-main-3-data
      csi.storage.k8s.io/pvc/name: pg-main-3-data
      csi.storage.k8s.io/pvc/namespace: cnpg-cluster-main
    volumeHandle: 095be9a5-0da9-4a6c-803f-95bee6d218c6