apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main
  namespace: default
spec:
  instances: 3

  storage:
    pvcTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd
        resources:
          requests:
            storage: 1Gi

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: pg-main-app-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-main-app-secret
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: app