---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgAnUCiBzRFYxcwbnOzSHepRooLC0Bg/aJw/ShNppJg7bp+go+KFqB6Nl1229f7NfcUQEusarJoEN7rhZHiqCeenH4nIs8skubiELXUW1G33vjM7lDXAwFdjwkUV0BdiiG+0JyJ5VReTuzP3Njxe5BiyGp85BmmNqPhp4pDCaXcxrOHjwN5HhMSbhtpB7Mc2YbUI+4llQnrpTHxvx2lmbMh1pFrun0kULGx72aLAaeQ2rJHAPTN2D3QQ+3xUl+V0jZx4e1UqAoIrT/RGHlp3e3rlivTJV0WVIK92mckzNpjg7Y3q5AbUFuV72iFY5eGjnnwDascaKvp7IqKAW7Mv4/fG1JGrCmiIPthTfTu0eCZ8Auob7Grf+EMgEaqVdppB27WNIc4kQ592KLIbTmcCp3NhxTs7CT1HsTdrQKtAs4OH3y5VPLjVcAuVnN7Tzrmu2rs4xniiDL0gsrEkyVsNhwbM7IQIm0ienzaH6LlcYBDr55Adw84i1+U7auyhqPag3JcEw5IIxaxuh0jOyP8I/tzeDRHimm+OEP3NsyE3NKIS10EExPVZrFpmn1vFDkc5ZJXCgDBkJNxUfFsf08WxfCbvBOgEMSQcsDeN2/I6vvotihRNOfJEdestsW8T1kOH+y/1dLxTn9YE0J79Jas44sseJZSGrH6dBQ9TYbcdTykmmlzj+FmgjD5l8xGoSgXeqJN4EBeJnUtUUPzvsIixfgAeJSr208W/XUWNNehW2EVt34201UPYV/kBVN+4zVFrkQYjTkEE5aylGp/AgU1AX2ZogOXu6nLRWviSu43rTO5j60yxGQq6rVrIGGdySNAlQig3W7MoSNDIqefYn95Cxs+mQMjC+jOFL4fbY+mPS42Tk6DWl/GrouMQsxutxOVH789YFz809ZUJYg+r33BPnl4ui2kKPjO2x8N5eYnWRMmrfTv4ttPMYb3E
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflare-tunnel
