# metallb-metal-lb-config.yaml
---
# Metallb address pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.50.241-192.168.50.250

---
# L2 configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-homelab
  namespace: metallb-system
spec:
  ipAddressPools:
    - cluster-pool
