apiVersion: v1
kind: Service
metadata:
  name: pg-main-lb
  namespace: cnpg-cluster-main
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: pg-main
    cnpg.io/instanceRole: primary
