---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-password
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAs3kAPUY1ntFZOZdKywD0gr6xC/KBphyUc/ZZ7l3Z6CG4K15ZiLFbtkLcS2OGpxXzYq6bIhgZubEnTEdubRqgCiTKO9I3Dldh5jLDSQruvbC6XpdU5kj0RB4peRP55h+ZGLkQ08R94qS98WbeJFPIX/akwmvyFxR0oJRcdfUdpPdc7xI5jf13h3wUm2jlp9YjINtmd8TTh2UyUW7mLlp22QC/hKcjXUQkc2k5Pg4YemgaooBEVMoJWMz5kKOX50ar4YIgbmZRL7iPUG+gzNKtOjR5siSYQIdSkOkuQ3GdZnidn6RL3+Csr28+SD+EcFY/d8DmhWXM+28pYbPYqz/ZnXjZl7c3miMD4xAfvRzFSlvdK1xhFY72gQ2sb+vEgqzW8A8mdp90N4RMP9HOtBvsxTdy1wv8Y/WKyUpiJ6wNNEH6RBYJ7NBfj9ouXCwsw0N2U91Czvvz+r21GQqKFu6ldWq31JQ1Itaf5mNERXbFQ3NPoIF97v1pkPGFJLovcPMw6KAxAk0N3x9AJejDpHlAMktV0PUZcWCZnR3aqDUSzISH2uLI/aLooFYuUMMqxQaTxN3H2rbAyJdblDX1nkIYJ7KfnKc68cNh29Bgu0kothpqdefV9H8qcnCkMbXrSoPvinxJKQ9xr0nJbcW+N30nMeVsdDU8doZ5Tu5eP00es9DhMGTN6XcrAPMOTNL/wCOlGA/iTfDR8Qw==
  template:
    metadata:
      name: pihole-password
      namespace: external-dns
